<?php
function log_menu(){
  $items=array();
  $items['login']=array(
    'title'=> 'You have successfully log in',
    'title callback' => 'show_username',
    'page callback'=>'welcome',
    'access callback'=>TRUE,
    'type'=>MENU_CALLBACK,
  );
  $items['logout']=array(
    'title'=>'Successfully log out',
    'page callback'=>'bye',
    'access callback'=>TRUE,
    'type'=> MENU_CALLBACK,
  );
  return $items;
}

function welcome(){
    user_cookie_save(array($GLOBALS['user']->name));

    $user_level = $GLOBALS['user']->roles;

    if(isset($user_level[3]) || isset($user_level[2])){ //admin or user 2 login
      return "Welcome " .$GLOBALS['user']->name;
    }else if (isset($user_level[1])) { //anonymous
      //user_level[0] is null
      return "Welcome visitor";
    }
}
function bye(){
  // var_dump($_COOKIE);
    return '<p>See you next time ' . $_COOKIE['Drupal_visitor_0'] . '</p>';
}
// in Drupal all enabled modules are given a chance to act whenever an event is about to take place.
function log_user_login()
{
  $_GET['destination']='login';
}
function log_user_logout()
{
  $_GET['destination']='logout';
}

function greeting_comment_insert(){
    drupal_set_message("Hey User");
}

function show_username() {
  $user_level = $GLOBALS['user']->roles;
  if(isset($user_level[3]) || isset($user_level[2])) {
    return 'You are sign in as ' . $GLOBALS['user']->name;
  }
}
